### PR TITLE
Update ITK to 5.4.0 and KDE runtime to 6.7

### PR DESCRIPTION
**Pull request by issakomi**
Info: runtime org.kde.Platform branch 6.6 is end-of-life

Closes https://github.com/AlizaMedicalImaging/AlizaMS/issues/68

### CODE REVIEW

**Comment by issakomi** [comment]
bot, build

**Comment by issakomi** [comment]
bot, build

**Comment by alcir** [comment]
bot, build

**Comment by issakomi** [comment]
@alcir  There is currently a problem with the builds https://github.com/flathub/flathub/issues/5806

**Comment by alcir** [comment]
> @alcir There is currently a problem with the builds [flathub/flathub#5806](https://github.com/flathub/flathub/issues/5806)

Yes yes, I see. I was just curious. :-)

**Comment by issakomi** [comment]
bot, build

**Pull request merged**
